### ISSUE TITLE
TrueOpenVR from requirements contains malware

### ISSUE THREAD

**Issue by momala454** [r57zone/Half-Life-Alyx-novr#38]
The portable zip from https://github.com/TrueOpenVR/TrueOpenVR-Core/releases
contains MouseEmulation.exe which is a malware :
https://www.virustotal.com/gui/file/dba88066394011d3df72abb99c35ed907d2a579ac8518a701463a9b07e79a6cf/detection

**Comment by r57zone** [comment]
Antiviruses, whose names I read for the first time. A good antivirus will not find any viruses there, because they are not there. 

The source code is [available to everyone](https://github.com/TrueOpenVR/TrueOpenVR-Tools/tree/master/MouseEmulation).

I will not delete anything because it is not a virus.

I do not think that you can trust antiviruses with strange names that are unclear by anyone.

Related - https://github.com/TrueOpenVR/TrueOpenVR-Core/issues/7
